-keep class com.shadow.mlbbcheat.MainActivity { *; }
-keep class com.shadow.mlbbcheat.services.OverlayService { *; }
-keep class com.shadow.mlbbcheat.services.AutoRetriService { *; }
-keep class com.shadow.mlbbcheat.services.ScriptService { *; }
